# Tipo de base de datos
quarkus.datasource.db-kind=postgresql

# Usuario y contraseña
quarkus.datasource.username=ecommerce
quarkus.datasource.password=secret

# URL de conexión
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce

# Hibernate / JPA
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

# Pool de conexiones
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.jdbc.min-size=2


